@startuml Repo_Map
/' 
2023.04.27
2023.07.17
start alpha ver 0.2
by Augstine_Kim (Kim Eui Cheol)
'/ 

object Data_list
object Model_list
 Model_list : VAR(Vector AutoRegression)
 Model_list : SVAR(Vector AutoRegression)
object Document_list
 Document_list :  Vector_AutoRegression

/'
  DataSet source
'/
package DataSet {

}

/'
  Models
'/
package Model {
    package VAR {
        object VAR_ex.ipynb
            VAR_ex.ipynb : use statsmodels
    }
    package SVAR {
        object SVAR_ex.ipynb
            SVAR_ex.ipynb : use statsmodels
    }
    package vECM_02 {
        object ex_VECM_02.ipynb
            ex_VECM_02.ipynb : use statsmodels
    }
    package Sadj {
        object X13_arima_sadj
            X13_arima_sadj : x13_arima_seats
    }
    package em_DFM {
        object em_TSA_DFM
            em_TSA_DFM : use statsmodels
    }
    package NN {
        object Neural_Network
            Neural_Network : pytorch
    }
}

/'
  Documents 
'/
package Document {
    map "Vector_AutoRegression" as doc {
        1=>VAR(Vector AutoRegressive) 모형 1
        2=>VAR(Vector AutoRegressive) 모형 2
        3=>VAR 분석절차 3
        4=>VAR 인과관계 검정 4
        5=>내생변수와 외생변수
        6=>단위근,공적분
        7=>SVAR(structural Vector AutoRegressive) 모형
    }

    map "concept understanding" as concept {
        1=>Dynamic Relationship
        2=>NDF(Non-Deliverable Forward 역외선물환)
        3=>선물환율과 현물환율
        4=>수익율의 변동성의 비대칭성(Asymmetry of Volatility)
        5=>옵션 내.외가격 상태(ITM, ATM,OTM)
        6=>필립스 곡선(Philips curve)
    }

 }

/'
  Relation connect
'/
Data_list --> DataSet
Model_list --> VAR
Model_list --> SVAR
Document_list --> doc

map "Repo_Map" as unit  {
    Document_list *---> Document_list
    Data_management *---> Data_list
    Model_list *---> Model_list
}


@enduml